import { useState,useContext } from 'react'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import Layout from '../../Components/Layout'
import { useRouter } from "next/router";
import { Context } from '../../Components/UserContext';


export default function Contact() {
  const { user,username_contexte} = useContext(Context);
  console.log(user)
  const supabase = useSupabaseClient()
  const [message, setMessage] = useState(null)
  const [newContenu, setNewContent] = useState()
  const [newTitle, setNewTitle] = useState()


  const router = useRouter()
 
  
  const addfield = async (newContenu,newTitle) => {
   
    const { error } = await supabase
      .from('post')
      .insert({ titre: newTitle,auteur_username:username_contexte,contenu: newContenu })
      .single()
      if (error) {
        setMessage('Sorry, an unexpected error occured.')
      } else {
        setMessage(
          <div>
            <h2 className="text-center mt-3">Confirmation</h2>
            <p>Votre poste a bien était ajouté</p>
            <button onClick={()=>{ router.push('/articles')}}>Retour a la page articles</button>
          </div>
        )
      }
  
  }
  return (
    <Layout>
      <Head>
        <title>Création de poste</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='wt-title'>
        Publication
      </h1>
      <div className="[&_span]:block grid gap-3">
        <label><span>
          Titre</span>
        <input
          type='text'
          placeholder='Titre de la publication'
          value={newTitle}
          onChange={(e) => {
            setNewTitle(e.target.value);
          }}
        />
</label>
<label><span>
          Descriptipon</span>
        <input
          type='text'
          placeholder='Description'
          value={newContenu}
          onChange={(e) => {
            setNewContent(e.target.value);
          }}
        />
</label>
        <button
          className="rounded py-1 px-3 text-white bg-slate-500 hover:bg-blue-500"
          onClick={() => addfield(newContenu, newTitle)}>
          Send
        </button>
      </div>

      {message &&
        <div
          aria-label="Overlow below the drawer dialog"
          className="fixed inset-0 bg-black/80 flex items-center justify-center"
          onClick={() => setMessage(null)}
          role="dialog"
        >
          <div
            aria-label="Alert pane"
            className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
          >
            {message} 
          </div>
        </div>
      }
    </Layout>
  )
}
