import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/Layout.js'

export default function Contacts() {
  return (
    <Layout>
      <Head>
        <title>WebTech - contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="space-y-10">
        <div class="space-y-20">
          <h1 class="font-bold">
            Contact
          </h1>
          <div>
            <p>
              In order to contact us, please make sure you fill in the following form
            </p>
          </div>
        </div>
        <form class="relative h-32 w-32 space-y-10">
          <div>
            <div>
              <label>
                <span>First name</span>
                <input type="text" name="firstname" />
              </label>
            </div>
            <div>
              <label>
                <span>Last name</span>
                <input type="text" name="lastname" />
              </label>
            </div>
            <div>
              <label>
                <span>Email</span>
                <input type="text" name="email" />
              </label>
            </div>
            <div>
              <label>
                <span>Your message</span>
                <textarea name="message" />
              </label>
            </div>
            <div class="relative h-32 w-36">
              <div>
                <input class="text-slate-100 bg-blue-400 rounded-md" 
                          type="submit" value="Send" />
              </div>
            </div>
          </div>
        </form>
      </div>
    </Layout>
  )
}
