import Head from "next/head";
import { useContext,useEffect } from "react";
import { useRouter } from "next/router";
import Layout from "/components/Layout.js";
import { Context } from "../components/UserContext";
import { data } from "autoprefixer";


export default function User({user_data}) {
  const { user,logout } = useContext(Context)

  const router = useRouter()
  useEffect(function(){
  if(!user){
    router.push('/login')
  }},[user])

  const deconnecter=function(){
    logout()
  }


  return (
    <Layout>
      <Head>
        <title>WebTech - User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p style={{ fontStyle: "italic" }}>
        Cette page affiche les données de l'utilisateurs connecté :
        
      </p>

     
      {user_data.map( users => (
        <div>
         <li>Username : {users.name}</li>
         <li>Addresse : {users.addresse}</li>
         <li>Email : {users.mail}</li>
         </div>
           
        ))}

    <button onClick={deconnecter}></button>
    </Layout>
  );
}
export const getStaticProps = async () => {
    const res = await fetch('https://my-json-server.typicode.com/yGrouzelle/Webtech-User/posts');
    const db = await res.json();
  console.log(db)
    return {
    
      props: { user_data: db }
    }
  }