import { useEffect, useState } from 'react'
//import {GetStaticProps, GetStaticPaths} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../../components/Layout.js'
import { db } from '../../api/articles.js'

export default function Article({
  article
}) {
  return (
    <Layout>
      <Head>
        <title>WebTech - articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        {article.title}
      </h1>
      <p style={{ fontStyle: 'italic' }}>This page fetch data at build time, excellent for SEO. {article.message}</p>

    </Layout>
  )
}



export  async function getStaticProps(context) {

const data = db
  return {
    props: {
      article :data
    }
  };
}

export async function getStaticPaths() {
  
  const paths= db.map( article => {
    return {
      params: { slug: article.slug.toString() }
    }
  })

  
  return{
    paths,
    fallback:false
  };
}

//export async function getStaticPaths() {
  //return {
   // paths: [{ params: { id: '1' } }, { params: { id: '2' } }],
    //fallback: false,
  //}
//}
