import { useEffect, useState } from 'react'
//import {GetStaticProps, GetStaticPaths} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../../components/Layout.js'
import { db } from '../../api/articles.js'

export default function Article({
  article
}) {
  return (
    <Layout>
      <Head>
        <title>WebTech - articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        {article.title}
      </h1>
      <p style={{ fontStyle: 'italic' }}>This page fetch data at build time, excellent for SEO. {article.message}</p>

    </Layout>
  )
}

/////////////////
/*
export const getStaticProps = async (context) => {
  const id = context.params.slug
  const res = await fetch('http://localhost:3000/api/articles/'+id)
  console.log(res);
  const data = await res.json()

  return {
    props: { article: data }
  }
}*/
///////////////////////

export const getStaticProps=async(context)=>{
const id=context.params.slug
console.log(id)



const data = db
console.log(data)
  return {
    props: {
      article :data
    }
  };
}
/*
export async function getStaticPaths() {
  
  const paths= db.map( article => {
    return {
      params: { slug: article.slug.toString() }
    }
  })

  
  return{
    paths,
    fallback:false
  };
}
*/
export const getStaticPaths = async () => {
  const res = await fetch('https://my-json-server.typicode.com/yGrouzelle/db-webtech/posts');
  const data = await res.json();

  // map data to an array of path objects with params (id)
  const paths = data.map(article => {
    return {
      params: { id: article.slug.toString() }
    }
  })
  return {
    paths,
    fallback: false
  }
}
